### ISSUE TITLE
Add option for search field to specify ONLY title, author, or abstract

### ISSUE THREAD

**Issue by JakeWags** [Dev-Lan/vispubs#14]
Hi Devin,

Please consider adding this feature. I think it will improve the search feature!
Currently you can search all 3 at once, but if I were to type "LLM" as if I wanted to see titles that include "LLM", it pulls up primarily papers involving author Jessical Hu*llm*an

**Comment by Dev-Lan** [comment]
I would suggest turning on the match case option, or turn on the regex option and search \bLLM\b. Both are toggle buttons inside the search bar.

**Comment by Dev-Lan** [comment]
Regex option:
[https://vispubs.com/?searchText=%5Cbllm%5Cb&useRegex=true](https://vispubs.com/?matchCase=true&searchText=LLM)

Match case option:
[https://vispubs.com/?matchCase=true&searchText=LLM](https://vispubs.com/?matchCase=true&searchText=LLM)

**Comment by Dev-Lan** [comment]
Closing for now since I think the current features can solve this specific request.

Please reopen if something cannot be solved with the current features.
