### ISSUE TITLE
Add accessibility information

### ISSUE THREAD

**Issue by domoritz** [Dev-Lan/vispubs#16]
In 2024, VIS is asking authors to indicate that they followed the [accessibility guide](https://ieeevis.org/year/2023/info/call-participation/make-pdf-accessible). I'm not sure how you are getting the publications data but it would be great to indicate whether an author checked this box.

**Comment by Dev-Lan** [comment]
I like this idea! It would help promote accessibility and make it easier for people to find accessible PDFs.

I'll have to look into if that data is publicly available anywhere. If not, it would be great if I could get access since it must exist somewhere.

I'm getting most of the data from dblp, but the process is still a bit ad-hoc for VIS since I want to publish it before it is available on dblp.

**Comment by domoritz** [comment]
> I like this idea! It would help promote accessibility and make it easier for people to find accessible PDFs.

Absolutely! 

For data, we definitely have the data at vis but I doubt that it will be propagated to dblp. If you get the data from VIS directly, you will also have information about open access with would also be great to have.

**Comment by Dev-Lan** [comment]
@domoritz, I have added this feature! Let me know if you have any feedback/suggestions.

One question I have is if you have any ideas on how to get this data for past publications or papers outside VIS?

**Comment by domoritz** [comment]
Awesome. Past data is hard. I think we have to rely on people submitting that information for now.

**Comment by Dev-Lan** [comment]
Also @domoritz, just in case you didn't see I added filtering on the tag in addition to the visual indication.

The filter can be done from the panel: https://vispubs.com/?filterPanelOpen=true&resourceFilter=Accessible

This might be a useful URL for people looking for only accessible VIS papers this year: https://vispubs.com/?resourceFilter=Accessible

**Comment by domoritz** [comment]
Neat. Good to see that many of the award winning papers are tagged.
