### ISSUE TITLE
The data (and code) needs a license

### ISSUE THREAD

**Issue by codydunne** [Dev-Lan/vispubs#8]
Have you considered adding a license to your data and code so that others can reuse it? E.g., they would need a license specified if they want to use your data in analysis papers. The [VIS open practices committee (inc. me) recommends](https://ieeevis.org/year/2024/info/open-practices/open-practices) CC BY 4.0 for data and Apache 2.0 for code.

**Comment by Dev-Lan** [comment]
Added! Thanks for the suggestion!
